# ============================================
# CONFIGURAÇÕES DA APLICAÇÃO
# ============================================
spring.application.name=b2b-order-service
server.port=8080

# ============================================
# CONEXÃO COM O MONGODB
# ============================================
spring.data.mongodb.uri=mongodb://admin:secret@localhost:27017/orders_db?replicaSet=rs0&authSource=admin

# ============================================
# CONFIGURAÇÕES DO SWAGGER / OPENAPI
# ============================================
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha

# ============================================
# LOGGING
# ============================================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.br.com.vpsconsulting.b2b_order_service=DEBUG